@extends('layouts.app')

@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
<div id="kt_content_container" class="container-xxl py-6">
@php($editing = $page->exists)
<form method="POST" action="{{ $editing ? route('service-pages.update', $page) : route('service-pages.store') }}">
@csrf @if($editing) @method('PUT') @endif
<div class="card mb-6"><div class="card-header"><h3 class="card-title">{{ $editing ? 'Edit' : 'Add' }} Dynamic Service Page</h3><div class="card-toolbar"><a href="{{ route('service-pages.index') }}" class="btn btn-light me-2">Back</a>@if($editing)<a target="_blank" href="{{ route('service-pages.preview', $page) }}" class="btn btn-light-info me-2">Preview</a>@endif<button class="btn btn-primary">Save Page</button></div></div>
<div class="card-body">@include('layouts.flash')
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-5">
 <div class="col-md-6"><label class="form-label required">Subject Master</label><select name="subject_id" class="form-select" required><option value="">Select Subject</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(old('subject_id',$page->subject_id)==$subject->id)>{{ $subject->name }}</option>@endforeach</select></div>
 <div class="col-md-6"><label class="form-label required">SEO Slug</label><div class="input-group"><span class="input-group-text">/</span><input name="slug" class="form-control" value="{{ old('slug',$page->slug) }}" placeholder="accounting-assignment-help" required></div></div>
 <div class="col-md-6"><label class="form-label required">Meta Title</label><input name="meta_title" class="form-control" maxlength="255" value="{{ old('meta_title',$page->meta_title) }}" required></div>
 <div class="col-md-6"><label class="form-label required">Meta Description</label><textarea name="meta_description" class="form-control" rows="2" required>{{ old('meta_description',$page->meta_description) }}</textarea></div>
</div></div></div>

<div class="card mb-6"><div class="card-header"><h3 class="card-title">Section 1 — Hero</h3></div><div class="card-body"><div class="row g-5">
 <div class="col-md-6"><label class="form-label required">Hero H1</label><input name="hero_heading" class="form-control" value="{{ old('hero_heading',$page->hero_heading) }}" required></div>
 <div class="col-md-6"><label class="form-label">Orange highlighted line</label><input name="hero_highlight" class="form-control" value="{{ old('hero_highlight',$page->hero_highlight) }}" placeholder="You Can Rely On"></div>
 <div class="col-12"><label class="form-label required">Hero Content</label><textarea name="hero_content" class="form-control" rows="4" required>{{ old('hero_content',$page->hero_content) }}</textarea></div>
</div></div></div>

<div class="row g-6 mb-6"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h3 class="card-title">Experts to show</h3></div><div class="card-body overflow-auto" style="max-height:350px">@forelse($experts as $expert)<label class="form-check form-check-custom form-check-solid mb-3"><input class="form-check-input" type="checkbox" name="expert_ids[]" value="{{ $expert->id }}" @checked(in_array($expert->id, old('expert_ids',$page->expert_ids ?: [])))><span class="form-check-label"><strong>{{ $expert->name }}</strong> — {{ $expert->subject ?: 'No subject' }}</span></label>@empty<p class="text-muted">Add experts in Expert Master first.</p>@endforelse</div></div></div>
<div class="col-lg-6"><div class="card h-100"><div class="card-header"><h3 class="card-title">“What Our Students Say” reviews</h3></div><div class="card-body overflow-auto" style="max-height:350px">@forelse($reviews as $review)<label class="form-check form-check-custom form-check-solid mb-3"><input class="form-check-input" type="checkbox" name="review_ids[]" value="{{ $review->id }}" @checked(in_array($review->id, old('review_ids',$page->review_ids ?: [])))><span class="form-check-label"><strong>{{ $review->name }}</strong> — {{ Str::limit($review->description,70) }}</span></label>@empty<p class="text-muted">Add reviews in Review Master first.</p>@endforelse</div></div></div></div>

<div class="card mb-6"><div class="card-header"><h3 class="card-title">Why Choose Section</h3><div class="card-toolbar"><button type="button" id="addWhyItem" class="btn btn-sm btn-light-primary">Add Benefit</button></div></div><div class="card-body"><div class="row g-5 mb-6"><div class="col-md-6"><label class="form-label">Main Heading</label><input name="why_heading" class="form-control" value="{{ old('why_heading',$page->why_heading) }}" placeholder="Why Choose Accounting Assignment Help from Us?"></div><div class="col-md-6"><label class="form-label">Subheading / Intro Content</label><textarea name="why_subheading" class="form-control" rows="3" placeholder="Short introductory paragraph...">{{ old('why_subheading',$page->why_subheading) }}</textarea></div></div><div id="whyItemRows" class="row g-5"></div></div></div>

<div class="card mb-6"><div class="card-header"><h3 class="card-title">Final CTA</h3></div><div class="card-body"><div class="row g-5"><div class="col-12"><label class="form-label">CTA Content</label><textarea name="cta_content" class="form-control" rows="3" placeholder="Accounting is a crucial subject...">{{ old('cta_content',$page->cta_content) }}</textarea></div><div class="col-md-6"><label class="form-label">Button Label</label><input name="cta_button_label" class="form-control" value="{{ old('cta_button_label',$page->cta_button_label) }}" placeholder="Get Free Quote Now"></div><div class="col-md-6"><label class="form-label">Button URL</label><input name="cta_button_url" class="form-control" value="{{ old('cta_button_url',$page->cta_button_url) }}" placeholder="/order-now"></div></div></div></div>

<div class="card mb-6"><div class="card-header"><h3 class="card-title">Dynamic FAQs</h3><div class="card-toolbar"><button type="button" id="addFaq" class="btn btn-sm btn-light-primary">Add FAQ</button></div></div><div class="card-body"><div id="faqRows"></div></div></div>
<div class="card"><div class="card-body d-flex justify-content-between align-items-center"><label class="form-check form-switch form-check-custom form-check-solid"><input type="hidden" name="is_published" value="0"><input class="form-check-input" type="checkbox" name="is_published" value="1" @checked(old('is_published',$page->is_published))><span class="form-check-label fw-bold">Publish on frontend</span></label><button class="btn btn-primary px-10">Save Page</button></div></div>
</form>
@php($faqValues = old('faqs', $page->faqs ?: [['question'=>'','answer'=>'']]))
@php($whyItemValues = old('why_items', $page->why_items ?: [['icon'=>'fas fa-clipboard-check','heading'=>'','content'=>'']]))
<template id="whyItemTemplate"><div class="why-item-row col-md-6"><div class="border rounded p-4 h-100"><div class="d-flex justify-content-between align-items-center mb-4"><strong>Benefit Item</strong><div><button type="button" class="btn btn-sm btn-light-info clone-why-item me-2"><i class="fa fa-copy"></i> Clone</button><button type="button" class="btn btn-sm btn-light-danger remove-why-item">Remove</button></div></div><label class="form-label">Icon</label><select class="form-select why-icon mb-3"><option value="fas fa-clipboard-check">Clipboard Check</option><option value="fas fa-edit">Edit / Custom Solution</option><option value="fas fa-check-square">Accuracy Check</option><option value="fas fa-link">Confidentiality Link</option><option value="fas fa-user-shield">Privacy Shield</option><option value="fas fa-headset">Support</option><option value="fas fa-award">Quality Award</option><option value="fas fa-clock">On-time Delivery</option><option value="fas fa-book-open">Academic Expertise</option></select><label class="form-label required">H3 Heading</label><input class="form-control why-heading mb-3" placeholder="Quality Assistance"><label class="form-label required">Content</label><textarea class="form-control why-content" rows="4" placeholder="Benefit description..."></textarea></div></div></template>
<template id="faqTemplate"><div class="faq-row border rounded p-4 mb-4"><div class="d-flex justify-content-end"><button type="button" class="btn btn-sm btn-light-danger remove-faq">Remove</button></div><label class="form-label required">Question</label><input class="form-control faq-question mb-3"><label class="form-label required">Answer</label><textarea class="form-control faq-answer" rows="3"></textarea></div></template>
<script>document.addEventListener('DOMContentLoaded',function(){const rows=document.getElementById('faqRows'),tpl=document.getElementById('faqTemplate');let index=0;function addFaq(faq={}){const node=tpl.content.cloneNode(true),row=node.querySelector('.faq-row');row.querySelector('.faq-question').name=`faqs[${index}][question]`;row.querySelector('.faq-answer').name=`faqs[${index}][answer]`;row.querySelector('.faq-question').value=faq.question||'';row.querySelector('.faq-answer').value=faq.answer||'';row.querySelector('.remove-faq').onclick=()=>row.remove();rows.appendChild(node);index++;}document.getElementById('addFaq').onclick=()=>addFaq();@json($faqValues).forEach(addFaq);});</script>
<script>document.addEventListener('DOMContentLoaded',function(){const rows=document.getElementById('whyItemRows'),tpl=document.getElementById('whyItemTemplate');let index=0;function addWhyItem(item={}){const node=tpl.content.cloneNode(true),row=node.querySelector('.why-item-row');row.querySelector('.why-icon').name=`why_items[${index}][icon]`;row.querySelector('.why-heading').name=`why_items[${index}][heading]`;row.querySelector('.why-content').name=`why_items[${index}][content]`;row.querySelector('.why-icon').value=item.icon||'fas fa-clipboard-check';row.querySelector('.why-heading').value=item.heading||'';row.querySelector('.why-content').value=item.content||'';row.querySelector('.remove-why-item').onclick=()=>row.remove();row.querySelector('.clone-why-item').onclick=()=>addWhyItem({icon:row.querySelector('.why-icon').value,heading:row.querySelector('.why-heading').value,content:row.querySelector('.why-content').value});rows.appendChild(node);index++;}document.getElementById('addWhyItem').onclick=()=>addWhyItem();@json($whyItemValues).forEach(addWhyItem);});</script>
</div>
</div>
@endsection
