<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $page->meta_title }}</title><meta name="description" content="{{ $page->meta_description }}"><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:#0f1838;background:#fff}.wrap{max-width:1180px;margin:auto;padding:0 22px}.preview{background:#fff3cd;color:#664d03;text-align:center;padding:8px;font-size:13px}.hero{background:linear-gradient(120deg,#fff 50%,#faf8ff);padding:55px 0 30px}.hero-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:55px;align-items:center}.crumb,.rating{font-size:12px;color:#667085;margin-bottom:24px}.stars{background:#24b56a;color:#fff;padding:4px 7px;border-radius:4px;margin-right:8px}.hero h1{font-size:46px;line-height:1.1;margin:0 0 12px}.orange{color:#ef5b12}.hero p{color:#5d6474;line-height:1.7}.quote{background:#fff;border:1px solid #eee;border-radius:22px;padding:28px;box-shadow:0 14px 45px #25115a14}.quote h2{text-align:center;margin-top:0}.field{border:1px solid #e9e6ef;border-radius:10px;padding:13px;margin:10px 0;color:#697080}.btn{display:block;background:#f45c08;color:#fff;border-radius:8px;text-align:center;padding:14px;font-weight:700}.features{padding:35px 0}.features h2,.section-title{text-align:center}.feature-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:20px}.feature{text-align:center;font-size:12px;color:#606778}.icon{width:48px;height:48px;margin:auto;border-radius:50%;display:grid;place-items:center;background:#f1ebff;color:#4a19a8;font-size:20px}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:16px}.card{border:1px solid #e9e6ef;border-radius:9px;overflow:hidden;background:#fff}.photo{height:135px;background:#f1eff5;display:grid;place-items:center;font-size:45px}.card-body{padding:14px}.purple{background:linear-gradient(100deg,#301076,#5c23be);color:#fff;padding:25px 0;margin:38px 0}.reviews{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.review{border:1px solid #e7e4ed;border-radius:8px;padding:22px;min-height:170px}.review:nth-child(2){background:#5b28bd;color:#fff}.content{padding:40px 0}.content-grid{display:grid;grid-template-columns:1fr 1fr;gap:40px}.content p{line-height:1.7;color:#596174}.faq{max-width:900px;margin:auto;padding:20px 0 60px}.faq details{border:1px solid #e5e1ed;border-radius:9px;padding:16px;margin:10px}.faq summary{font-weight:700;cursor:pointer}@media(max-width:800px){.hero-grid,.content-grid{grid-template-columns:1fr}.feature-grid{grid-template-columns:repeat(2,1fr)}.cards{grid-template-columns:1fr 1fr}.reviews{grid-template-columns:1fr}.hero h1{font-size:36px}}
</style></head><body><div class="preview">Admin preview — draft pages are not visible on the frontend.</div>
<section class="hero"><div class="wrap hero-grid"><div><div class="crumb">Home › Subjects › {{ $page->subject->name }} Assignment Help</div><div class="rating"><span class="stars">★★★★★</span>Rated 4.9/5 by 25,000+ UK Students</div><h1>{{ $page->hero_heading }}<br><span class="orange">{{ $page->hero_highlight }}</span></h1><p>{{ $page->hero_content }}</p></div><div class="quote"><h2>✨ Get Instant Quote ✨</h2><div class="field">Academic Level &nbsp; — &nbsp; Select Level</div><div class="field">Subject &nbsp; — &nbsp; {{ $page->subject->name }}</div><div class="field">Assignment Type &nbsp; — &nbsp; Select Type</div><div class="field">Deadline &nbsp; — &nbsp; Select Deadline</div><div class="field">Email Address</div><div class="btn">Get Price Now →</div></div></div></section>
<section class="features"><div class="wrap"><h2>Why Students Choose Our {{ $page->subject->name }} Assignment Help?</h2><div class="feature-grid">@foreach(['Qualified Experts','100% Original','On-Time Delivery','24/7 Support','UK-Based Experts','Affordable Pricing'] as $i=>$feature)<div class="feature"><div class="icon">{{ ['♙','✓','◷','☏','⌖','£'][$i] }}</div><h3>{{ $feature }}</h3><p>Professional academic support you can rely on.</p></div>@endforeach</div></div></section>
@if($experts->isNotEmpty())<section><div class="wrap"><h2 class="section-title">Our {{ $page->subject->name }} Assignment Experts</h2><div class="cards">@foreach($experts->take(5) as $expert)<div class="card"><div class="photo">👤</div><div class="card-body"><strong>{{ $expert->name }}</strong><p>{{ $expert->subject ?: $page->subject->name }} Expert</p><small>★ 4.9 · {{ $expert->finish_order ?: 800 }}+ Orders</small></div></div>@endforeach</div></div></section>@endif
<section class="purple"><div class="wrap"><strong>UP TO 30% OFF ON YOUR FIRST ORDER</strong> &nbsp; · &nbsp; Plagiarism Report &nbsp; · &nbsp; AI Report &nbsp; · &nbsp; Unlimited Revisions &nbsp; · &nbsp; 24/7 Support</div></section>
@if($reviews->isNotEmpty())<section><div class="wrap"><h2 class="section-title">What Our Students Say</h2><div class="reviews">@foreach($reviews->take(3) as $review)<div class="review"><p>“{{ $review->description }}”</p><strong>{{ $review->name }}</strong><br><small>{{ $review->location }} · {{ str_repeat('★', (int)($review->customer_rating ?: 5)) }}</small></div>@endforeach</div></div></section>@endif
@if($page->why_heading || $page->why_items)<section class="content"><div class="wrap"><div style="max-width:900px;margin:0 auto 28px;text-align:center"><h2>{{ $page->why_heading }}</h2><p>{{ $page->why_subheading }}</p></div><div class="content-grid">@foreach($page->why_items ?: [] as $item)<div style="display:grid;grid-template-columns:48px 1fr;gap:14px"><span class="icon">✓</span><div><h3 style="margin:0 0 6px">{{ $item['heading'] }}</h3><p style="margin:0">{{ $item['content'] }}</p></div></div>@endforeach</div></div></section>@endif
@if($page->faqs)<section class="faq"><h2 class="section-title">Frequently Asked Questions</h2>@foreach($page->faqs as $faq)<details><summary>{{ $faq['question'] }}</summary><p>{{ $faq['answer'] }}</p></details>@endforeach</section>@endif
</body></html>
